name: elo-competition

channels:
  - conda-forge
  - pytorch

dependencies:
  - black=19.10b0
  - cudatoolkit=10.1
  - ipywidgets=7.5.1
  - jupyterlab=1.2.4
  - jupytext=1.3.0
  - kaggle=1.5.6
  - matplotlib=3.1.2
  - pandas=0.25.3
  - pytest=5.3.2
  - python=3.7.5
  - pytorch=1.3.1
  - scikit-learn=0.22
  - seaborn=0.9.0
  - tqdm=4.40.2
