name: elo-competition

channels:
  - conda-forge
  - pytorch

dependencies:
  - cudatoolkit=10.1
  - ipywidgets=7.5.1
  - jupyterlab=1.1.4
  - jupytext=1.2.4
  - kaggle=1.5.6
  - matplotlib=3.1.1
  - pandas=0.25.2
  - python=3.7
  - pytorch=1.3.0
  - scikit-learn=0.21.3
  - seaborn=0.9.0
  - tqdm=4.36.1
