name: elo-competition

channels:
  - conda-forge
  - pytorch

dependencies:
  - ipywidgets=7.5.1
  - jupyterlab=2.1.0
  - jupytext=1.4.2
  - kaggle=1.5.6
  - matplotlib=3.2.1
  - pandas=1.0.3
  - pre-commit=2.2.0
  - pyarrow=0.16.0
  - pytest=5.4.1
  - python=3.8.2
  - pytorch=1.4.0
  - scikit-learn=0.22.2.post1
  - seaborn=0.10.0
  - tqdm=4.45.0
